version: "3"
volumes:
  my-vol:
    external: true

services:
 web:
  build:
     context: /var/lib/docker/volumes/my-vol/_data
     dockerfile: Dockerfile.dev
  ports: 
     - "3000:3000"
  volumes:
     - /app/node_modules
     - my-vol:/app


